In [1]:
import numpy as np
lst1 = [1, 2, 3]
arr1 = np.array(lst1)
# arr1 - np.array([1,2,3], dtype = np.uint8)

In [2]:
print(type(lst1))
print(type(arr1))

<class 'list'>
<class 'numpy.ndarray'>


In [3]:
arr1 = np.array([[1,2,3],[4,5,6]],np.int16)
arr1

array([[1, 2, 3],
       [4, 5, 6]], dtype=int16)

In [4]:
arr1 = np.array([[[1, 2, 3], [4, 5, 6]],
                 [[7, 8, 9], [0, 0, 0]],
                 [[-1, -1, -1], [1, 1, 1]]], np.int16)
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [ 0,  0,  0]],

       [[-1, -1, -1],
        [ 1,  1,  1]]], dtype=int16)

In [5]:
arr1 = np.array([1,2,3], dtype=np.uint8)
print(arr1[0])
print(arr1[-1])

1
3


In [6]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]], np.int16)
print(arr1[1,1])
print(arr1[0,:])
print(arr1[:,2])

5
[1 2 3]
[3 6]


In [7]:
arr1 = np.array([[[1, 2, 3], [4, 5, 6]],
                 [[7, 8, 9], [0, 0, 7]],
                 [[-1, -1, -1], [1, 1, 1]]], np.int16)
print(arr1 [0, 0, 0])
print(arr1 [1, 1, 2])
print(arr1 [:, 1, 1])

1
7
[5 0 1]


In [8]:
x2 = np.array([[[1, 2, 3], [4, 5, 6]],[[0, -1, -2], [1, -4, -5]]], np.int16)
print(x2.ndim)
print(x2.shape)

print(x2.dtype)
print(x2.size)
print(x2.nbytes)
print(x2.T)

print(x2.T.shape) # print(x2.shape[::-1])
# for a 3d matrix, it has 6 kind of transpose matrices(you can permute the axes freely and get 3*2 kind of matrix) 
# x2.T will give the one that reverses every axes ([x,y,z] -> [z,y,x])

3
(2, 2, 3)
int16
12
24
[[[ 1  0]
  [ 4  1]]

 [[ 2 -1]
  [ 5 -4]]

 [[ 3 -2]
  [ 6 -5]]]
(3, 2, 2)


In [9]:
print(np.inf)
print(np.NAN)
print(np.NINF)
print(np.NZERO)
print(np.PZERO)
print(np.e)
print(np.euler_gamma)
print(np.pi)


inf
nan
-inf
-0.0
0.0
2.718281828459045
0.5772156649015329
3.141592653589793


In [20]:
x = np.empty([5,3],dtype= np.uint8)
print(x)    # random numbers



x = np.eye(4, dtype=np.uint8)
print(x)    # a matrix of all zeros except the diagonal elements of all the zeros. 
            # The diagonal has all the ones.
x = np.eye(4, dtype = np.uint8, k=1)    # set the position of the diagonal
print(x)
x = np.eye(4, dtype=np.uint8, k=-1)
print(x)

[[  0   0   0]
 [  0   0   0]
 [  0   0  32]
 [128  99 137]
 [ 43   2   0]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]


In [19]:
y = np.identity(4, dtype=np.uint8)
print(y)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [22]:
x= np.ones((2,3,3),dtype=np.int16)
print(x)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [33]:
x1 = np.arange(1,10,3)  # [1,10) step size = 3
x2 = np.arange(10)  # [0,10) step size = 1
print(x1,x2)

[1 4 7] [0 1 2 3 4 5 6 7 8 9]


In [37]:
np.linspace(0,20,num = 30)    # 30 evenly spaced values between [0,20]

array([ 0.        ,  0.68965517,  1.37931034,  2.06896552,  2.75862069,
        3.44827586,  4.13793103,  4.82758621,  5.51724138,  6.20689655,
        6.89655172,  7.5862069 ,  8.27586207,  8.96551724,  9.65517241,
       10.34482759, 11.03448276, 11.72413793, 12.4137931 , 13.10344828,
       13.79310345, 14.48275862, 15.17241379, 15.86206897, 16.55172414,
       17.24137931, 17.93103448, 18.62068966, 19.31034483, 20.        ])

In [36]:
np.logspace(0.1,2,num=10, base=10)   
# 10 evenly spaced values [base**0.1, base**2] within a logarithmic space

array([  1.25892541,   2.04696827,   3.32829814,   5.41169527,
         8.79922544,  14.30722989,  23.26305067,  37.82489906,
        61.50195043, 100.        ])

In [40]:
np.geomspace(0.1,20,num=10)
# 10 evenly spaced values [0.1, 2] within a logarithmic space so no base needed

array([ 0.1       ,  0.18016482,  0.32459363,  0.58480355,  1.05361028,
        1.89823509,  3.41995189,  6.16155028, 11.10094616, 20.        ])